function l(b,a,c,d){b.s.kb(b.nb,a,c,d)}function n(b,a,c,d){b.s.ca?l(b,a,c,d):b.s.Ee()._OnMessageFromDOM({type:"event",component:b.nb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.s.C(b.nb,a,c)}function r(b,a){for(const [c,d]of a)p(b,c,d)}function u(b){b.Sb||(b.s.pd(b.Wd),b.Sb=!0)}window.fb=class{constructor(b,a){this.s=b;this.nb=a;this.Sb=!1;this.Wd=()=>this.Na()}ed(){}Na(){}};
window.nf=class{constructor(){this.ad=-1}j(){-1!==this.ad&&(self.clearTimeout(this.ad),this.ad=-1)}};"use strict";class aa{constructor(b){this.Ic=b;this.Lc=!1;this.Sc=!0}}function ba(b,a){const c=a.elementId,d=b.jd(c,a),e=new aa(d);b.qb.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Sc=!!a.isVisible;d.addEventListener("focus",()=>{ca(b,"elem-focused",c)});d.addEventListener("blur",()=>{ca(b,"elem-blurred",c)});b.Ob&&document.body.appendChild(d)}
function v(b,a,c){p(b,a,d=>{const e=w(b,d.elementId);return c(e,d)})}function w(b,a){b=b.qb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Ic}function ca(b,a,c){var d;d||(d={});d.elementId=c;l(b,a,d)}function x(b,a,c,d){d||(d={});d.elementId=c;n(b,a,d)}
window.pe=class extends self.fb{constructor(b){super(b,"html-element");this.qb=new Map;this.Ob=!0;r(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const c=w(this,a);this.Ob&&c.parentElement.removeChild(c);this.qb.delete(a)}],["set-visible",a=>{if(this.Ob){var c=this.qb.get(a.elementId),d=c.Ic;c.Lc?d.style.display=a.isVisible?"":"none":c.Sc=!!a.isVisible}}],["update-position",a=>{if(this.Ob){var c=this.qb.get(a.elementId),d=c.Ic;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";a=a.fontSize;null!==a&&(d.style.fontSize=a+"em");c.Lc||(c.Lc=!0,c.Sc&&(d.style.display=""))}}],["update-state",a=>{const c=w(this,a.elementId);this.od(c,a)}],["focus",a=>this.Cc(a)],["set-css-style",a=>{const c=w(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{w(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{w(this,a.elementId).removeAttribute(a.name)}]]);v(this,"get-element",
a=>a)}jd(){throw Error("required override");}od(){throw Error("required override");}Cc(b){var a=w(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),ea=/android/i.test(navigator.userAgent),fa=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ha=0;
function ia(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.cf?new Promise(c=>{const d="c3_resolve_"+ha;++ha;self[d]=c;a.textContent=b.gf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ja=!1,ka=!1;function la(){if(!ja){try{new Worker("blob://",{get type(){ka=!0}})}catch(b){}ja=!0}return ka}let y=new Audio;
const ma={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;async function na(b){b=await oa(b);return(new TextDecoder("utf-8")).decode(b)}
function oa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const pa=[];let A=0;window.RealFile=window.File;const B=[],qa=new Map,ta=new Map;let ua=0;const va=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");va.push(b)};const xa=new Set(["cordova","playable-ad","instant-games"]);let ya=!1;
window.wa=class b{constructor(a){this.ca=a.jf;this.ya=null;this.ba="";this.$a=a.ff;this.Eb={};this.Ta=this.ua=null;this.Qb=[];this.J=this.na=null;this.Pc=!1;this.Dd=0;this.tb=null;this.Za=-1;this.Ze=()=>this.Me();this.Ya=[];this.bd=null;this.Xd=[];this.v=a.Yd;this.Tb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&la()||(this.ca=!1);this.ca&&fa&&(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===
this.v&&this.ca)if(ea){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.va()?self.chrome.webview.addEventListener("message",c=>this.ud(c.data)):"macos-wkwebview"===this.v&&(self.C3WrapperOnMessage=c=>this.ud(c));this.Wb=this.ra=null;"html5"!==this.v||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");
this.C("runtime","cordova-fetch-local-file",c=>this.Ie(c));this.C("runtime","create-job-worker",()=>this.Je());this.C("runtime","send-wrapper-extension-message",c=>this.Pe(c));"cordova"===this.v?document.addEventListener("deviceready",()=>this.sd(a)):this.sd(a)}j(){this.vc();this.ya&&(this.ya=this.ya.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Ta&&(this.Ta.j(),this.Ta=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}te(){return da&&"cordova"===this.v}rc(){const a=
navigator.userAgent;return da&&xa.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}re(){return ea}ld(){return ea&&xa.has(this.v)}va(){return"windows-webview2"===this.v||!!("preview"===this.v&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async sd(a){"macos-wkwebview"===this.v?this.Ea({type:"ready"}):this.va()&&(this.Se(),this.Xd=(await this.He()).registeredComponentIds);if("playable-ad"===this.v){this.ra=self.c3_base64files;this.Wb={};await this.Ae();
for(let d=0,e=a.bb.length;d<e;++d){var c=a.bb[d];this.Wb.hasOwnProperty(c)?a.bb[d]={cf:!0,gf:this.Wb[c]}:this.ra.hasOwnProperty(c)&&(a.bb[d]=URL.createObjectURL(this.ra[c]))}a.kc=[]}if("nwjs"===this.v&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.pd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.ef?this.ba=a.ef:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.lf&&(this.Eb=a.lf);
c=new MessageChannel;this.ya=c.port1;this.ya.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Le(d));this.tb=new self.ue(this);await za(this.tb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ca?await this.Ge(a,c.port2):
await this.Fe(a,c.port2)}xc(a){a=this.Eb.hasOwnProperty(a)?this.Eb[a]:a.endsWith("/workermain.js")&&this.Eb.hasOwnProperty("workermain.js")?this.Eb["workermain.js"]:"playable-ad"===this.v&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async mc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.v&&this.Tb)return a=await this.Fb(d.bf?a:this.$a+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=
new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}pa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}rd(a){var c=this.ba,d=location.href,e=this.pa(),f=this.ia(),g=window.devicePixelRatio,h=b.ib(),k=a.sf,m=window.cr_previewImageBlobs||this.ra,q=window.cr_previewProjectFileBlobs,C=window.cr_previewProjectFiles,z=window.cr_swClientId||
"";a=a.Yd;var t=(new URLSearchParams(self.location.search)).has("debug"),D=this.tb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:m,previewProjectFileBlobs:q,previewProjectFileSWUrls:C,swClientId:z,exportType:a,isDebug:t,ife:!!self.rf,jobScheduler:{inputPort:D.Oc,outputPort:D.Wc,maxNumWorkers:D.We},supportedAudioFormats:ma,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.$a+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.$a+"opus.wasm.wasm",isFileProtocol:this.Tb,isiOSCordova:this.te(),isiOSWebView:this.rc(),isWebView2Wrapper:this.va(),wrapperComponentIds:this.Xd,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ge(a,c){const d=this.xc(a.kf);"preview"===this.v?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const m=q=>{this.ua.removeEventListener("message",m);q.data&&"ok"===q.data.type?h():k()};this.ua.addEventListener("message",m);this.ua.postMessage({type:"construct-worker-init",
"import":(new URL(d,this.ba)).toString()})})):this.ua=await this.mc(d,this.ba,{type:"module",name:"Runtime",bf:!0});this.J=document.createElement("canvas");this.J.style.display="none";const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.kc||[],g=a.bb;f=await Promise.all(f.map(h=>this.Oa(h)));g=await Promise.all(g.map(h=>this.Oa(h)));if("cordova"===this.v)for(let h=0,k=a.jc.length;h<
k;++h){const m=a.jc[h],q=m[0];if(q===a.cd||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))m[1]=await this.Oa(q)}this.ua.postMessage(Object.assign(this.rd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.jc,mainProjectScript:a.cd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...Aa(this.tb)]);this.Qb=B.map(h=>new h(this));this.qd();Ba(this.na);self.c3_callFunction=(h,k)=>{var m=this.na;return m.s.nd(m.nb,
"js-invoke-function",{name:h,params:k})};"preview"===this.v&&(self.goToLastErrorScript=()=>this.kb("runtime","go-to-last-error-script"))}async Fe(a,c){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Qb=B.map(g=>new g(this));this.qd();var d=a.bb.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.kc)){var e=[...a.kc].map(g=>
g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Oa(g)));await Promise.all(d.map(g=>ia(g)));d=self.C3_ProjectScriptsStatus;e=a.cd;const f=a.jc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Oa(h),await ia(h),"preview"!==this.v||d[g]||this.vd(g,"main script did not run to completion")}catch(k){this.vd(g,k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Oa(h),await ia(h);"preview"===this.v&&"object"!==typeof self.mf.pf?
(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.rd(a),{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:va}),Ba(this.na),this.td(),this.Ta=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ta,a))}vd(a,c){this.Kb();console.error(`[Preview] Failed to load project main script (${a}): `,
c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}td(){this.Kb()}Kb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Je(){const a=await Ca(this.tb);return{outputPort:a,transferables:[a]}}Ee(){if(this.ca)throw Error("not available in worker mode");return this.Ta}kb(a,c,d,e,f){this.ya.postMessage({type:"event",component:a,handler:c,
dispatchOpts:e||null,data:d,responseId:null},f)}nd(a,c,d,e,f){const g=ua++,h=new Promise((k,m)=>{ta.set(g,{resolve:k,reject:m})});this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ke(a);if("result"===c)this.Ne(a);else if("runtime-ready"===c)this.Oe();else if("alert-error"===c)this.Kb(),alert(a.message);else if("creating-runtime"===c)this.td();else throw Error(`unknown message '${c}'`);
}Ke(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=qa.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Jb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Jb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Jb(f,!1,""+h)}):this.Jb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Jb(a,
c,d){let e;d&&d.transferables&&(e=d.transferables);this.ya.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ne(a){const c=a.responseId,d=a.isOk;a=a.result;const e=ta.get(c);d?e.resolve(a):e.reject(a);ta.delete(c)}C(a,c,d){let e=qa.get(a);e||(e=new Map,qa.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static cb(a){if(B.includes(a))throw Error("DOM handler already added");B.push(a)}qd(){for(const a of this.Qb)if("runtime"===a.nb){this.na=
a;return}throw Error("cannot find runtime DOM handler");}Le(a){this.kb("debugger","message",a)}Oe(){for(const a of this.Qb)a.ed()}static ib(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ya)}static Lb(a){ya=!!a}pd(a){this.Ya.push(a);this.Ec()}Re(a){a=this.Ya.indexOf(a);if(-1===a)throw Error("invalid callback");this.Ya.splice(a,1);this.Ya.length||this.vc()}Ec(){-1===this.Za&&this.Ya.length&&(this.Za=requestAnimationFrame(this.Ze))}vc(){-1!==
this.Za&&(cancelAnimationFrame(this.Za),this.Za=-1)}Me(){this.Za=-1;for(const a of this.Ya)a();this.Ec()}Da(a){this.na.Da(a)}Ma(a){this.na.Ma(a)}Dc(){this.na.Dc()}Ib(a){this.na.Ib(a)}se(){return!!ma["audio/webm; codecs=opus"]}async Te(a){a=await this.nd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}we(a){this.Pc=!0;this.Dd=a}qe(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}md(a){return!this.qe(a)}async Oa(a){return"cordova"===
this.v&&(a.startsWith("file:")||this.Tb&&this.md(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Fb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ie(a){const c=a.filename;switch(a.as){case "text":return await this.oe(c);case "buffer":return await this.Fb(c);default:throw Error("unsupported type");}}hd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async oe(a){a=
await this.hd(a);return await na(a)}wc(){if(pa.length&&!(8<=A)){A++;var a=pa.shift();this.Be(a.filename,a.hf,a.af)}}Fb(a){return new Promise((c,d)=>{pa.push({filename:a,hf:e=>{A--;this.wc();c(e)},af:e=>{A--;this.wc();d(e)}});this.wc()})}async Be(a,c,d){try{const e=await this.hd(a),f=await oa(e);c(f)}catch(e){d(e)}}ud(a){if("entered-fullscreen"===a)b.Lb(!0),E(this.na);else if("exited-fullscreen"===a)b.Lb(!1),E(this.na);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.bd(a),
this.bd=null):"extension-message"===c?this.kb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Pe(a){this.Ea({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ea(a){this.va()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.v&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Se(){window.moveTo=(a,c)=>
{this.Ea({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ea({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}He(){return this.va()?new Promise(a=>{this.bd=a;this.Ea({type:"wrapper-init"})}):Promise.resolve()}async Ae(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.ze(c,d));await Promise.all(a)}async ze(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),this.Wb[a]=c.str;else{let d=
await this.De(c);d||(d=this.Ce(c));this.ra[a]=d}}async De(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Ce(a){a=this.Qe(a);return this.ye(a.data,a.df)}Qe(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,
c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{df:a,data:d}}ye(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const F=self.wa;
function Da(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Ea=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),H={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Fa={dispatchUserScriptEvent:!0},Ga={dispatchRuntimeEvent:!0};
function Ha(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ia(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function I(b){b=URL.createObjectURL(b);try{return await Ia(b)}finally{URL.revokeObjectURL(b)}}
function Ja(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ka(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await I(b);var d=await Ja(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await I(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await I(b)}
function La(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ma=new Set(["input","textarea","datalist","select"]),Na=new Set(["canvas","body","html"]);function J(b){b.target.tagName&&Na.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Oa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await I(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ka(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Pa=!1;document.addEventListener("pause",()=>Pa=!0);document.addEventListener("resume",()=>Pa=!1);function Ba(b){b.Cd=!0;b.Tc=b.s.pa();b.ub=b.s.ia()}function E(b){if(!b.$){var a=F.ib();a&&"any"!==b.Zc&&Qa(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.pa(),innerHeight:b.ia()})}}async function Ra(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Sa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ta(b){return await self.C3_GetSvgImageSize(b.blob)}function Ua(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Va(b){self.setTimeout(()=>{b.Bd=!0},1E3);"cordova"===b.s.v?(document.addEventListener("pause",()=>Wa(b,!0)),document.addEventListener("resume",()=>Wa(b,!1))):document.addEventListener("visibilitychange",()=>Wa(b,"hidden"===document.visibilityState));b.$b=!("hidden"!==document.visibilityState&&!Pa);return{isSuspended:b.$b}}
function Xa(b){b.xd||(b.xd=!0,window.addEventListener("deviceorientation",a=>{b.$||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},H)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},H)}))}
function Ya(b){b.wd||(b.wd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},H)}}))}async function Za(b){await Ha(b.url)}
function $a(b,a){b.Ed=a.message;-1===b.Jc&&(b.Jc=setTimeout(()=>{b.Jc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Ed)},250))}function ab(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:F.ib(),innerWidth:b.pa(),innerHeight:b.ia()})}function Wa(b,a){b.$b!==a&&((b.$b=a)?b.s.vc():b.s.Ec(),l(b,"visibilitychange",{hidden:a}))}
function bb(b,a,c){"Backspace"===c.key&&J(c);if(!b.$){var d=Ea.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},H)}}function cb(b,a,c,d){b.$||Da(c)||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function db(b){window!==window.top&&window.focus();gb(b.target)&&document.activeElement&&!gb(document.activeElement)&&document.activeElement.blur()}
function K(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.zb);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},H);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),cb(b,d,c,Fa),b.zb=c.buttons)}}
function hb(b,a,c){if(!b.$&&!Da(c)){var d=b.zb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");n(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},H);b.zb=c.buttons;cb(b,c.type,c,Fa)}}
function L(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];n(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
H)}}function ib(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function jb(b,a,c,d){const e=b.pa(),f=b.ia();b.ab=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:F.ib()}):10>d&&kb(b,e,f,d+1)}
function kb(b,a,c,d){-1!==b.ab&&clearTimeout(b.ab);b.ab=setTimeout(()=>jb(b,a,c,d),48)}
function Qa(b){b=b.Zc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function gb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
F.cb(class extends self.fb{constructor(b){super(b,"runtime");this.Jd=!0;this.Cd=!1;this.ab=-1;this.Zc="any";this.$b=this.wd=this.xd=!1;this.fc=document.createElement("div");this.fc.className="c3-screen-reader-text";this.fc.setAttribute("aria-live","polite");document.body.appendChild(this.fc);this.Ha=null;this.$=!1;this.Ed="";this.Jc=-1;this.Bd=!1;this.Tc=b.pa();this.ub=b.ia();this.da=this.Db=0;b.C("canvas","update-size",d=>{var e=this.s;e.Pc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=
d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Jd&&(e.style.display="",this.Jd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Ra(d));b.C("runtime","raster-svg-image",d=>Sa(d));b.C("runtime",
"get-svg-image-size",d=>Ta(d));b.C("runtime","set-target-orientation",d=>{this.Zc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Ua(d));b.C("runtime","go-to-script",d=>Ua(d));b.C("runtime","before-start-ticking",()=>Va(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ha||(this.Ha=document.createElement("div"),this.Ha.id="inspectOutline",document.body.appendChild(this.Ha));var e=this.Ha;e.style.display=
"";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ha&&(this.Ha.style.display="none")});b.C("runtime","enable-device-orientation",()=>Xa(this));b.C("runtime","enable-device-motion",()=>Ya(this));b.C("runtime","add-stylesheet",d=>Za(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>this.Ac(d));
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.fc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.s.J.style.display="";this.s.we(d.duration)});b.C("runtime","export-to-video-progress",d=>$a(this,d));b.C("runtime","exported-to-video",d=>{window.$e({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.$e({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||La(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",J);window.addEventListener("gesturehold",J);c.addEventListener("selectstart",J);c.addEventListener("gesturehold",
J);window.addEventListener("touchstart",J,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",J,{passive:!1}),c.addEventListener("pointerdown",J)):c.addEventListener("touchstart",J);this.zb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Oa,{passive:!1});window.addEventListener("wheel",Oa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.Cd){var d=this.pa();var e=this.ia();if(this.s.ld()){if(this.Bd){if(this.Tc===
d&&e<this.ub){this.Db=this.ub-e;ib(this,this.ub,this.Db);d=void 0;break a}0<this.Db&&(this.Db=0,ib(this,e,this.Db))}this.Tc=d;this.ub=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:F.ib()});this.s.rc()&&(-1!==this.ab&&clearTimeout(this.ab),jb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>E(this));window.addEventListener("webkitfullscreenchange",()=>E(this));window.addEventListener("mozfullscreenchange",()=>
E(this));window.addEventListener("fullscreenerror",d=>ab(this,d));window.addEventListener("webkitfullscreenerror",d=>ab(this,d));window.addEventListener("mozfullscreenerror",d=>ab(this,d));if(b.rc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):La(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Ua=new Set;this.Yb=new WeakSet;this.xa=!1}ed(){window.addEventListener("focus",()=>{l(this,"window-focus",null,Ga)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}l(this,"window-blur",{parentHasFocus:a},Ga);this.zb=0});window.addEventListener("focusin",a=>{a=a.target;(Ma.has(a.tagName.toLowerCase())||La(a))&&
l(this,"keyboard-blur",null,Ga)});window.addEventListener("keydown",a=>bb(this,"keydown",a));window.addEventListener("keyup",a=>bb(this,"keyup",a));window.addEventListener("dblclick",a=>cb(this,"dblclick",a,H));window.addEventListener("wheel",a=>{this.$||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},H)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{db(a);K(this,"pointerdown",a)}),this.s.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{K(this,"pointermove",a)}):window.addEventListener("pointermove",a=>K(this,"pointermove",a)),window.addEventListener("pointerup",a=>K(this,"pointerup",a)),window.addEventListener("pointercancel",a=>K(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{db(a);hb(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>hb(this,
"pointermove",a)),window.addEventListener("mouseup",a=>hb(this,"pointerup",a)),window.addEventListener("touchstart",a=>{db(a);L(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>L(this,"pointermove",a)),window.addEventListener("touchend",a=>L(this,"pointerup",a)),window.addEventListener("touchcancel",a=>L(this,"pointercancel",a)));const b=()=>this.Dc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.s.re()&&!this.s.ld()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{ib(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}))}pa(){return this.s.pa()}ia(){return this.s.ia()}Dc(){var b=[...this.Ua];this.Ua.clear();if(!this.xa)for(const a of b)(b=a.play())&&b.catch(()=>{this.Yb.has(a)||this.Ua.add(a)})}Da(b){if("function"!==typeof b.play)throw Error("missing play function");
this.Yb.delete(b);let a;try{a=b.play()}catch(c){this.Ua.add(b);return}a&&a.catch(()=>{this.Yb.has(b)||this.Ua.add(b)})}Ma(b){this.Ua.delete(b);this.Yb.add(b)}Ib(b){this.xa=!!b}Ac(b){alert(b.message)}});"use strict";
async function za(b){if(b.Ue)throw Error("already initialised");b.Ue=!0;var a=b.za.xc(("playable-ad"===b.za.v?b.za.$a:"")+"dispatchworker.js");b.Hc=await b.za.mc(a,b.mb,{name:"DispatchWorker"});a=new MessageChannel;b.Oc=a.port1;b.Hc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Wc=await Ca(b)}function Aa(b){return[b.Oc,b.Wc]}
async function Ca(b){const a=b.Kd.length;var c=b.za.xc(("playable-ad"===b.za.v?b.za.$a:"")+"jobworker.js");c=await b.za.mc(c,b.mb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Hc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Kd.push(c);return e.port1}
self.ue=class{constructor(b){this.za=b;this.mb=b.ba;this.mb="preview"===b.v?this.mb+"workers/":this.mb+b.$a;this.We=Math.min(navigator.hardwareConcurrency||2,16);this.Hc=null;this.Kd=[];this.Wc=this.Oc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.wa({jf:!0,kf:"workermain.js",bb:["scripts/c3runtime.js"],jc:[],cd:"",ff:"scripts/",kc:[],Yd:"html5"}));"use strict";
async function lb(b,a){a=a.type;let c=!0;0===a?c=await mb():1===a&&(c=await nb());l(b,"permission-result",{type:a,result:c})}async function mb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function nb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.wa.cb(class extends self.fb{constructor(b){super(b,"touch");p(this,"request-permission",a=>lb(this,a))}});"use strict";function ob(){}
function pb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>l(b,"sw-message",a.data))}
function qb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.wa.cb(class extends self.fb{constructor(b){super(b,"browser");this.v="";r(this,[["get-initial-state",a=>{this.v=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
pb(this)],["alert",a=>this.Ac(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Cc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>qb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.s.va()?window.open(c,"_blank"):this.qf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.s.va()||"macos-wkwebview"===this.v)self.wa.Lb(!0),this.s.Ea({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(ob)}}],["exit-fullscreen",()=>{if(this.s.va()||"macos-wkwebview"===this.v)self.wa.Lb(!1),this.s.Ea({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(ob)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",
()=>{l(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{l(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{l(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{l(this,"backbutton")})}Ac(b){alert(b.message)}Cc(b){b=b.isFocus;if("nwjs"===this.v){const a="nwjs"===this.v?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";
function rb(b){b.replaceChildren?b.replaceChildren():b.innerHTML=""}function M(b){b=Array.from(b.querySelectorAll("script:not([c3-executed])"));for(const c of b){b=c.parentNode;var a=b.replaceChild;const d=document.createElement("script");d.text=c.text;const e=c.attributes;for(let f=0,g=e.length;f<g;++f){const h=e[f];d.setAttribute(h.name,h.value)}d.setAttribute("c3-executed","");a.call(b,d,c)}}function N(b,a,c){return a?c?Array.from(b.querySelectorAll(a)):(b=b.querySelector(a))?[b]:[]:[b]}
function O(b){return b?{isOk:!0,html:b.innerHTML,text:b.textContent}:{isOk:!1}}
self.wa.cb(class extends self.pe{constructor(b){super(b);v(this,"set-content",(a,c)=>{{const e=c.str,f=c.type,g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)"html"===f?(k.innerHTML=e,M(k)):k.textContent=e;d=O(a)}}catch(h){console.warn("[HTML element] Failed to set content: ",h),d=O(null)}}return d});v(this,"insert-content",(a,c)=>{{const e=c.str,f=c.type,g=c["at-end"]?"beforeend":"afterbegin",h=c.selector;c=c["is-all"];try{const k=N(a,h,c);if(0===
k.length)var d=O(null);else{for(const m of k)"html"===f?(m.insertAdjacentHTML(g,e),M(m)):m.insertAdjacentText(g,e);d=O(a)}}catch(k){console.warn("[HTML element] Failed to insert content: ",k),d=O(null)}}return d});v(this,"remove-content",(a,c)=>{{const e=c["is-clear"],f=c.selector;c=c["is-all"];if(f)try{const g=N(a,f,c);if(0===g.length)var d=O(null);else{for(const h of g)e?rb(h):h.remove();d=O(a)}}catch(g){console.warn("[HTML element] Failed to remove content: ",g),d=O(null)}else rb(a),d=O(a)}return d});
v(this,"set-content-class",(a,c)=>{{const e=c.mode,f=c["class-array"],g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)for(const m of f)switch(e){case "add":k.classList.add(m);break;case "toggle":k.classList.toggle(m);break;case "remove":k.classList.remove(m)}d=O(a)}}catch(h){console.warn("[HTML element] Failed to set class: ",h),d=O(null)}}return d});v(this,"set-content-attribute",(a,c)=>{{const e=c.mode,f=c.attribute,g=c.value,h=c.selector;c=c["is-all"];
try{const k=N(a,h,c);if(0===k.length)var d=O(null);else{for(const m of k)switch(e){case "set":m.setAttribute(f,g);break;case "remove":m.removeAttribute(f)}d=O(a)}}catch(k){console.warn("[HTML element] Failed to set attribute: ",k),d=O(null)}}return d});v(this,"set-content-css-style",(a,c)=>{{const e=c.prop,f=c.value,g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)e.startsWith("--")?k.style.setProperty(e,f):k.style[e]=f;d=O(a)}}catch(h){console.warn("[HTML element] Failed to set style: ",
h),d=O(null)}}return d});v(this,"get-element-box",(a,c)=>{(a=(c=c.selector)?a.querySelector(c):a)?(a=a.getBoundingClientRect(),a={isOk:!0,left:a.left,top:a.top,right:a.right,bottom:a.bottom}):a={isOk:!1};return a});v(this,"insert-img-element",(a,c)=>{a:{const e=c.blobUrl;var d=c.width;const f=c.height,g=c.selector,h=c.insertAt;let k=a;if(g&&(k=a.querySelector(g),!k)){a={isOk:!1};break a}d=new Image(d,f);d.src=e;c.id&&(d.id=c.id);c["class"]&&(d.className=c["class"]);0===h?k.prepend(d):1===h?k.append(d):
k.replaceChildren?k.replaceChildren(d):(rb(k),k.append(d));a=O(a)}return a});v(this,"set-scroll-position",(a,c)=>{a:{const d=c.selector,e=c.direction;c=c.position;if(d&&(a=a.querySelector(d),!a)){c=void 0;break a}"left"===e?a.scrollLeft=c:a.scrollTop=c;c=void 0}return c})}jd(b,a){const c=document.createElement(a.tag);a["style-attribute"]&&c.setAttribute("style",a["style-attribute"]);c.style.position="absolute";var d=a["stop-input-events-mode"];if(0<d){let e=null;1===d?e=f=>{f.target!==c&&f.stopPropagation()}:
2===d&&(e=f=>f.stopPropagation());c.addEventListener("pointerdown",e);c.addEventListener("pointermove",e);c.addEventListener("pointerrawupdate",e);c.addEventListener("pointerup",e);c.addEventListener("mousedown",e);c.addEventListener("mouseup",e);c.addEventListener("dblclick",e)}a["allow-context-menu"]&&c.addEventListener("contextmenu",e=>e.stopPropagation());c.addEventListener("click",e=>{e=e.target;const f=[];for(;e;){f.push({targetId:"string"===typeof e.id?e.id:"",targetClass:"string"===typeof e.className?
e.className:""});if(e===c)break;e=e.parentNode}x(this,"click",b,{chain:f})});c.addEventListener("animationend",e=>{const f=e.target;x(this,"animationend",b,{targetId:"string"===typeof f.id?f.id:"",targetClass:"string"===typeof f.className?f.className:"",animationName:e.animationName})});a.id&&(c.id=a.id);a.className&&(c.className=a.className);a["css-color"]&&(c.style.color=a["css-color"]);a["css-background-color"]&&(c.style.backgroundColor=a["css-background-color"]);a["allow-text-selection"]||(c.style.userSelect=
"none",c.style.webkitUserSelect="none");d=a.str;"html"===a.type?(c.innerHTML=d,M(c)):c.textContent=d;x(this,"initial-content",b,{html:c.innerHTML,text:c.textContent});return c}od(b,a){b.innerHTML=a.html;M(b)}});"use strict";const sb=180/Math.PI;
async function tb(b,a){if(a.isiOSCordova||a.isSafari)b.bc=!0;b.$c=a.timeScaleMode;b.Pd=["equalpower","HRTF","soundfield"][a.panningModel];b.Ad=["linear","inverse","exponential"][a.distanceModel];b.Qd=a.refDistance;b.Od=a.maxDistance;b.Sd=a.rolloffFactor;if(b.s.Pc)b.bc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.s.Dd)});else{var c={latencyHint:a.latencyHint};b.Vd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");ub(b);b.g.onstatechange=()=>{"running"!==b.g.state&&ub(b);l(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Qa=b.g.createGain();b.Qa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function vb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,m=a.pos,q=a.panning,C=a.stereoPan;let z=a.off;0<z&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),z=z-a.performanceTime/1E3+a.contextTime):z=z-performance.now()/1E3+b.g.currentTime);b.Ld=g.slice(0);wb(b,g);try{b.R=await xb(b,c,d,e,g,f);if(q){Q(b.R,!0);var t=b.R,D=q.innerAngle,ra=q.outerAngle,sa=q.outerGain;if(t.sb){yb(t,q.x,q.y,q.z,q.angle);var G=self.eb.xe;t.sa[0]!==G(D)&&
(t.sa[0]=G(D),t.F.coneInnerAngle=G(D));t.sa[1]!==G(ra)&&(t.sa[1]=G(ra),t.F.coneOuterAngle=G(ra));t.sa[2]!==sa&&(t.sa[2]=sa,t.F.coneOuterGain=sa)}q.hasOwnProperty("uid")&&(b.R.qa=q.uid)}else"number"===typeof C&&0!==C?(R(b.R,!0),zb(b.R,C)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,m,z)}catch(Lb){console.error("[Construct] Audio: error starting playback: ",Lb);return}finally{c=g.join(" ");d=b.Bb.get(c);if(!d)throw Error("expected pending tag");d.dd--;0===d.dd&&(d.resolve(),b.Bb.delete(c))}u(b)}
async function Ab(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await Bb(b,c);for(const h of S(b,c))if(!h.Sa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ka=d;h.Ra=g;h.Ud=a}T(b)}async function Cb(b,a){const c=a.tags;a=a.rate;await Bb(b,c);for(const d of S(b,c))d.ma!==a&&(d.ma=a,d.Fa())}async function Db(b,a){const c=a.tags;a=a.pos;await Bb(b,c);for(const d of S(b,c))d.sc(a)}
async function Eb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await xb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function Fb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function Gb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.de(b,...e);else if("delay"===c)d=new self.be(b,...e);else if("convolution"===c){var g=d=new self.ae(b,f.ja,...e),h=a.bufferType;g.yd=a.bufferOriginalUrl;g.zd=h}else if("flanger"===c)d=new self.ee(b,...e);else if("phaser"===
c)d=new self.ge(b,...e);else if("gain"===c)d=new self.fe(b,...e);else if("stereopan"===c)d=new self.ie(b,...e);else if("tremolo"===c)d=new self.je(b,...e);else if("ringmod"===c)d=new self.he(b,...e);else if("distortion"===c)d=new self.ce(b,...e);else if("compressor"===c)d=new self.$d(b,...e);else if("analyser"===c)d=new self.Zd(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let m=g.la.get(h);m||(m=[],g.la.set(h,m));d.Id=m.length;d.Yc=h;m.push(d);Hb(g,h)}Ib(b)}
async function Jb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ba()&&1===c||!e.Ba()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.la.values())for(const g of f)g.j();b.la.clear();b.hc=a.timeScale;b.Kc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.xa=a.isSilent;b.s.Ib(b.xa);b.Xb=a.masterVolume;b.Qa.gain.value=
b.Xb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>Gb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Kb(b,f,c)));T(b)}
async function Mb(b,a){try{const c=b.g.suspend(a.time);b.Hd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.s.kb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Nb(d)),b.Hd=!0);await c}catch(c){Nb(c)}}
function ub(b){b.Rb||(b.Nc=!1,window.addEventListener("pointerup",b.Aa,!0),window.addEventListener("touchend",b.Aa,!0),window.addEventListener("click",b.Aa,!0),window.addEventListener("keydown",b.Aa,!0),b.Rb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ka)if(g.hb()===c)return await Ob(g),g;if(f)return null;if(e&&(b.bc||b.Gd)){f=0;for(let h=0,k=b.ka.length;h<k;++h)g=b.ka[h],b.ka[f]=g,g.Ba()?g.j():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.Vd;e&&f&&(b.Gd=!0);c=!e||b.bc||f?new self.me(b,a,c,d,e,f):new self.ke(b,a,c,d,e);b.ka.push(c);await Ob(c);b.Nd.has(a)||(l(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Nd.add(a));return c}
function Pb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Qb(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.ga()}function Hb(b,a){a=a.toLowerCase();let c=b.ga();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ga()):e.U(d[f+1].N())}}for(const f of Rb(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Ia&&b.Uc===a&&(b.Ia.disconnect(),b.Ia.connect(c))}
function*Rb(b,a){if(a)for(const c of b.H)Pb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Sb(b,a,c){return c?b.s.Te(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Tb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Pb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function xb(b,a,c,d,e,f){for(const g of b.H)if(g.hb()===c&&(g.lc()||f))return g.oa=e,g;a=await P(b,a,c,d,f);e="html5"===a.Fc?new self.le(a.u,a,e):new self.ne(a.u,a,e);b.H.push(e);return e}
function wb(b,a){a=a.join(" ");let c=b.Bb.get(a);if(!c){let d=null;c={dd:0,promise:new Promise(e=>d=e),resolve:d};b.Bb.set(a,c)}c.dd++}function Bb(b,a){return(b=b.Bb.get((0===a.length?b.Ld:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Pa.size)u(b);else for(const a of b.H)if(!a.I&&!a.O()){u(b);break}}function Ub(b,a,c,d){l(b,"trigger",{type:a,tags:c,aiid:d})}function Ib(b){b.Qc||(b.Qc=!0,Promise.resolve().then(()=>Vb(b)))}
function Vb(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.gb());l(b,"fxstate",{fxstate:a});b.Qc=!1}
async function Kb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,m=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await xb(b,d,e,f,h,g)}catch(C){console.error("[Construct] Audio: error loading audio state: ",C);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Wa[0]=f[0],b.Wa[1]=f[1],b.Wa[2]=f[2],f=d.orient,b.Va[0]=f[0],b.Va[1]=f[1],b.Va[2]=f[2],e.setPosition(...b.Wa),e.setOrientation(...b.Va),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),zb(b,d));c.Play(k,m,q,0);a.isPlaying||c.jb();c.zc(a)}}}function Nb(b){console.error("[Audio] Offline rendering error: ",b)}
self.eb=class extends self.fb{constructor(b){super(b,"audio");this.Qa=this.g=null;this.Rb=this.Nc=!1;this.Aa=()=>{if(!this.Nc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Rb&&(this.Nc=!0,window.removeEventListener("pointerup",this.Aa,!0),window.removeEventListener("touchend",this.Aa,!0),window.removeEventListener("click",this.Aa,!0),window.removeEventListener("keydown",
this.Aa,!0),this.Rb=!1)}};this.ka=[];this.H=[];this.R=null;this.Ld=[];this.Nd=new Set;this.Md=-1;this.Bb=new Map;this.Xb=1;this.xa=!1;this.$c=0;this.hc=1;this.Kc=0;this.Pd="HRTF";this.Ad="inverse";this.Qd=600;this.Od=1E4;this.Sd=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.Gd=this.bc=!1;this.Vd=this.s.se();this.la=new Map;this.Pa=new Set;this.Hd=this.Qc=!1;this.Uc="";this.Ia=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ia&&this.Ia.disconnect();this.Uc=c.toLowerCase();this.Ia=this.g.createMediaStreamSource(a);
this.Ia.connect(Qb(this,this.Uc))};this.Pb=null;self.C3Audio_GetOutputStream=()=>{this.Pb||(this.Pb=this.g.createMediaStreamDestination(),this.Qa.connect(this.Pb));return this.Pb.stream};self.C3Audio_DOMInterface=this;r(this,[["create-audio-context",a=>tb(this,a)],["play",a=>vb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ca()}],["stop-all",()=>{for(const a of this.H)a.Ca()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.jb():d.Hb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>Ab(this,a)],["set-master-volume",a=>{this.Xb=a.vol;this.Qa.gain.value=this.Xb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Wb(d,a)}],["set-silent",a=>{this.xa=a.isSilent;this.s.Ib(this.xa);for(const c of this.H)c.Mb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.tc(a)}],["set-playback-rate",a=>Cb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),zb(d,a)}],["seek",a=>Db(this,a)],["preload",a=>Eb(this,a)],["unload",a=>Fb(this,a)],["unload-all",()=>{for(const a of this.ka)a.j();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.uc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Gb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.la.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Ib(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.la.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.la.delete(a);Hb(this,a)}}],["tick",a=>{this.hc=a.timeScale;this.Kc=a.gameTime;this.Md=a.tickCount;if(0!==this.$c)for(var c of this.H)c.Fa();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==
c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.qa===a&&yb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Jb(this,a)],["offline-render-audio",a=>Mb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ga(){return this.Qa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ga()}Gb(){return this.xa}Da(b){this.s.Da(b)}Ma(b){this.s.Ma(b)}Na(){for(var b of this.Pa)b.Na();
b=this.g.currentTime;for(var a of this.H)a.Na(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.gb());l(this,"state",{tickCount:this.Md,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Pa].map(c=>({tag:c.Yc,index:c.Id,peak:c.Xa,rms:c.Rd,binCount:c.l.frequencyBinCount,freqBins:c.Fd}))});0===a.length&&0===this.Pa.size&&this.Sb&&(this.s.Re(this.Wd),this.Sb=!1)}static xe(b){return b*sb}static kd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static ve(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.wa.cb(self.eb);"use strict";function Ob(b){b.Vb||(b.Vb=b.yc());return b.Vb}self.fd=class{constructor(b,a,c,d,e){this.u=b;this.Ye=a;this.Ja=c;this.T=d;this.Ve=e;this.Fc="";this.Vb=null}j(){this.Vb=this.u=null}yc(){}V(){return this.u.V()}oc(){return this.Ye}hb(){return this.Ja}nc(){return this.T}Ba(){return this.Ve}ha(){}};"use strict";
self.ke=class extends self.fd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Fc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.vb=this.wb=null;this.M.addEventListener("canplaythrough",()=>!0);this.Ab=this.V().createGain();this.yb=null;this.M.addEventListener("canplay",()=>{this.wb&&(this.wb(),this.vb=this.wb=null);!this.yb&&this.M&&(this.yb=this.V().createMediaElementSource(this.M),this.yb.connect(this.Ab))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.vb&&(this.vb(f),this.vb=this.wb=null)})}j(){Tb(this.u,this);this.Ab.disconnect();this.Ab=null;this.yb.disconnect();this.yb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}yc(){return new Promise((b,a)=>{this.wb=b;this.vb=a;this.M.src=this.Ja})}W(){return this.M}ha(){return this.M.duration}};"use strict";
async function Xb(b){if(b.Ga)return b.Ga;var a=b.u.s;if("cordova"===a.v&&a.md(b.Ja)&&a.Tb)b.Ga=await a.Fb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ga=await a.arrayBuffer()}}async function Yb(b){if(b.ja)return b.ja;b.ja=await Sb(b.u,b.Ga,b.Xe);b.Ga=null}
self.me=class extends self.fd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Fc="webaudio";this.ja=this.Ga=null;this.Xe=!!f}j(){Tb(this.u,this);this.ja=this.Ga=null;super.j()}async yc(){try{await Xb(this),await Yb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}ha(){return this.ja?this.ja.duration:0}};"use strict";let Zb=0;
function Q(b,a){a=!!a;b.sb!==a&&(b.sb=a,b.sb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Pd,b.F.distanceModel=b.u.Ad,b.F.refDistance=b.u.Qd,b.F.maxDistance=b.u.Od,b.F.rolloffFactor=b.u.Sd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ga())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ga())))}
function R(b,a){a=!!a;b.Ub!==a&&(b.Ub=a,b.Ub?(Q(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.ga())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.ga())))}function zb(b,a){b.Ub&&b.Xc!==a&&(b.fa.pan.value=a,b.Xc=a)}function U(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Ra=-1;b.G.gain.value=b.pc()}function Wb(b,a){a=!!a;b.Sa!==a&&(b.Sa=a,b.Mb())}
function yb(b,a,c,d,e){if(b.sb){var f=b.Wa,g=b.Va,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Rc?b.u.Kc:performance.now()/1E3}
self.gd=class{constructor(b,a,c){this.u=b;this.P=a;this.oa=c;this.Nb=Zb++;this.G=this.V().createGain();this.G.connect(this.ga());this.F=null;this.sb=!1;this.Wa=[0,0,0];this.Va=[0,0,0];this.sa=[0,0,0];this.fa=null;this.Ub=!1;this.Xc=0;this.I=!0;this.Y=this.ta=this.K=!1;this.Ka=1;this.Sa=!1;this.ma=1;b=this.u.$c;this.Rc=1===b&&!this.Ba()||2===b;this.Ra=this.qa=-1;this.Ud=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ga(){return Qb(this.u,0<this.oa.length?this.oa[0]:"")}oc(){return this.P.oc()}hb(){return this.P.hb()}nc(){return this.P.nc()}Ba(){return this.P.Ba()}O(){}lc(){}IsPlaying(){return!this.I&&!this.K&&!this.O()}La(){}ha(){return this.P.ha()}Play(){}Ca(){}jb(){}Hb(){}Na(b){-1!==this.Ra&&b>=this.Ra&&(this.Ra=-1,this.Ud&&this.Ca(),Ub(this.u,"fade-ended",this.oa,this.Nb))}pc(){const b=this.Ka;return isFinite(b)?b:0}Gb(){return this.u.Gb()}Mb(){}tc(){}Fa(){}sc(){}uc(){}qc(){}gb(){var b=
this.Nb,a=this.oa,c=this.ha(),d=-1===this.Ra?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Wa,orient:this.Va,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.La(),playbackRate:this.ma,uid:this.qa,bufferOriginalUrl:this.oc(),bufferUrl:"",bufferType:this.nc(),isMusic:this.Ba(),isLooping:this.Y,isMuted:this.Sa,resumePosition:this.qc(),pan:f,stereoPan:this.fa?
this.Xc:null}}zc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Fa());Wb(this,b.isMuted)}};"use strict";
self.le=class extends self.gd{constructor(b,a,c){super(b,a,c);this.P.Ab.connect(this.G);this.P.onended=()=>this.Bc()}j(){this.Ca();this.P.Ab.disconnect();super.j()}W(){return this.P.W()}Bc(){this.I=!0;this.qa=-1;Ub(this.u,"ended",this.oa,this.Nb)}O(){return this.W().ended}lc(){return this.I?!0:this.O()}La(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.hb()}' to position '${c}': `,e)}this.u.Da(d);this.K=this.I=!1;this.Y=b;this.ma=1}Ca(){const b=this.W();b.paused||b.pause();this.u.Ma(b);this.I=!0;this.K=!1;this.qa=-1}jb(){if(!(this.K||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Ma(b);this.K=!0}}Hb(){!this.K||this.I||this.O()||(this.u.Da(this.W()),this.K=!1)}Mb(){this.W().muted=this.Sa||this.Gb()}tc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.W().loop=b)}Fa(){let b=this.ma;this.Rc&&(b*=this.u.hc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}sc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}qc(){return this.La()}uc(b){b?this.IsPlaying()?(this.W().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.u.Da(this.W()),this.ta=!1)}};"use strict";
function W(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.lb=null}
self.ne=class extends self.gd{constructor(b,a,c){super(b,a,c);this.o=null;this.Zb=d=>this.Bc(d);this.Mc=!0;this.lb=null;this.S=this.ac=this.cc=0;this.Vc=1}j(){this.Ca();W(this);this.Zb=null;super.j()}Bc(b){this.K||this.ta||b.target!==this.lb||(this.I=this.Mc=!0,this.qa=-1,W(this),Ub(this.u,"ended",this.oa,this.Nb))}O(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Mc}lc(){return!this.o||this.I?!0:this.O()}La(){let b;b=this.K?this.S:this.ac+(V(this)-this.cc)*this.ma;this.Y||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Vc=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.P.ja;this.o.connect(this.G);this.lb=this.o;this.o.onended=this.Zb;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Mc=!1;this.Y=b;this.ma=1;this.cc=V(this);this.ac=c}Ca(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.qa=-1}jb(){this.K||this.I||this.O()||(this.S=this.La(),this.Y&&(this.S%=this.ha()),this.K=!0,this.o.stop(0))}Hb(){!this.K||this.I||this.O()||(W(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.P.ja,this.o.connect(this.G),this.lb=this.o,this.o.onended=this.Zb,this.o.loop=this.Y,U(this,this.Ka),this.Fa(),this.o.start(0,this.S),this.cc=V(this),this.ac=this.S,this.K=!1)}pc(){return super.pc()*this.Vc}Mb(){this.Vc=this.Sa||this.Gb()?0:1;U(this,this.Ka)}tc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Fa(){let b=this.ma;this.Rc&&(b*=this.u.hc);this.o&&(this.o.playbackRate.value=b)}sc(b){this.I||this.O()||(this.K?this.S=b:(this.jb(),this.S=
b,this.Hb()))}qc(){return this.S}uc(b){b?this.IsPlaying()?(this.ta=!0,this.S=this.La(),this.Y&&(this.S%=this.ha()),this.o.stop(0)):this.ta=!1:this.ta&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.P.ja,this.o.connect(this.G),this.lb=this.o,this.o.onended=this.Zb,this.o.loop=this.Y,U(this,this.Ka),this.Fa(),this.o.start(0,this.S),this.cc=V(this),this.ac=this.S,this.ta=!1)}zc(b){super.zc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Id=-1;this.T=this.Yc="";this.m=null}j(){this.g=null}N(){}U(){}gb(){return{type:this.T,tag:this.Yc,params:this.m}}}
self.de=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.be=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.xb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.pb=X(this);this.pb.gain.value=c;this.A.connect(this.xb);this.A.connect(this.h);this.xb.connect(this.i);this.xb.connect(this.X);this.X.connect(this.pb);this.pb.connect(this.xb)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.xb.disconnect();
this.X.disconnect();this.pb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.eb.kd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.pb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.ae=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.zd=this.yd="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.ob=this.g.createConvolver();this.ob.normalize=c;this.ob.buffer=a;this.A.connect(this.ob);this.A.connect(this.h);this.ob.connect(this.i)}j(){this.A.disconnect();this.ob.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}gb(){const b=super.gb();b.bufferOriginalUrl=this.yd;b.bufferUrl="";b.bufferType=this.zd;return b}};
self.ee=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.rb=X(this);this.rb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.rb);this.rb.connect(this.X);this.B.connect(this.L);
this.L.connect(this.X.delayTime);this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.X.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.rb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.rb.gain,a/100,c,d)}}};
self.ge=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.fe=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.eb.kd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.ie=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.je=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.he=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Cb=X(this);this.Cb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Cb.gain);this.B.start(0);this.A.connect(this.Cb);this.A.connect(this.h);this.Cb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Cb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.ce=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.A=X(this);this.ec=X(this);this.dc=X(this);b=d;.01>b&&(b=.01);this.ec.gain.value=b;this.dc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.ic=this.g.createWaveShaper();this.Gc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Gc[32768+e]=f,this.Gc[32768-
e-1]=-f;this.ic.curve=this.Gc;this.A.connect(this.ec);this.A.connect(this.h);this.ec.connect(this.ic);this.ic.connect(this.dc);this.dc.connect(this.i)}j(){this.A.disconnect();this.ec.disconnect();this.ic.disconnect();this.dc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.$d=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.Zd=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Fd=new Float32Array(this.l.frequencyBinCount);this.Td=new Uint8Array(a);this.Rd=this.Xa=0;b=this.u;b.Pa.add(this);T(b)}j(){this.u.Pa.delete(this);this.l.disconnect();super.j()}Na(){this.l.getFloatFrequencyData(this.Fd);this.l.getByteTimeDomainData(this.Td);const b=this.l.fftSize;let a=this.Xa=0;for(var c=0;c<b;++c){let d=(this.Td[c]-
128)/128;0>d&&(d=-d);this.Xa<d&&(this.Xa=d);a+=d*d}c=self.eb.ve;this.Xa=c(this.Xa);this.Rd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
