function l(b,a,c,d){b.v.Eb(b.kb,a,c,d)}function n(b,a,c,d){b.v.ca?l(b,a,c,d):b.v.ze()._OnMessageFromDOM({type:"event",component:b.kb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.v.C(b.kb,a,c)}function r(b,a){for(const [c,d]of a)p(b,c,d)}function u(b){b.Qb||(b.v.md(b.Sd),b.Qb=!0)}window.cb=class{constructor(b,a){this.v=b;this.kb=a;this.Qb=!1;this.Sd=()=>this.La()}bd(){}La(){}};
window.ff=class{constructor(){this.Zc=-1}j(){-1!==this.Zc&&(self.clearTimeout(this.Zc),this.Zc=-1)}};"use strict";class aa{constructor(b){this.Gc=b;this.Jc=!1;this.Qc=!0}}function ba(b,a){const c=a.elementId,d=b.fd(c,a),e=new aa(d);b.nb.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Qc=!!a.isVisible;d.addEventListener("focus",()=>{ca(b,"elem-focused",c)});d.addEventListener("blur",()=>{ca(b,"elem-blurred",c)});b.Mb&&document.body.appendChild(d)}
function v(b,a,c){p(b,a,d=>{const e=w(b,d.elementId);return c(e,d)})}function w(b,a){b=b.nb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Gc}function ca(b,a,c){var d;d||(d={});d.elementId=c;l(b,a,d)}function x(b,a,c,d){d||(d={});d.elementId=c;n(b,a,d)}
window.ke=class extends self.cb{constructor(b){super(b,"html-element");this.nb=new Map;this.Mb=!0;r(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const c=w(this,a);this.Mb&&c.parentElement.removeChild(c);this.nb.delete(a)}],["set-visible",a=>{if(this.Mb){var c=this.nb.get(a.elementId),d=c.Gc;c.Jc?d.style.display=a.isVisible?"":"none":c.Qc=!!a.isVisible}}],["update-position",a=>{if(this.Mb){var c=this.nb.get(a.elementId),d=c.Gc;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";a=a.fontSize;null!==a&&(d.style.fontSize=a+"em");c.Jc||(c.Jc=!0,c.Qc&&(d.style.display=""))}}],["update-state",a=>{const c=w(this,a.elementId);this.ld(c,a)}],["focus",a=>this.zc(a)],["set-css-style",a=>{const c=w(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{w(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{w(this,a.elementId).removeAttribute(a.name)}]]);v(this,"get-element",
a=>a)}fd(){throw Error("required override");}ld(){throw Error("required override");}zc(b){var a=w(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),ea=/android/i.test(navigator.userAgent),fa=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ha=0;
function ia(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.We?new Promise(c=>{const d="c3_resolve_"+ha;++ha;self[d]=c;a.textContent=b.$e+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ja=!1,ka=!1;function la(){if(!ja){try{new Worker("blob://",{get type(){ka=!0}})}catch(b){}ja=!0}return ka}let y=new Audio;
const ma={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;async function na(b){b=await oa(b);return(new TextDecoder("utf-8")).decode(b)}
function oa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const pa=[];let A=0;window.RealFile=window.File;const B=[],qa=new Map,ta=new Map;let va=0;const wa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");wa.push(b)};const xa=new Set(["cordova","playable-ad","instant-games"]);let ya=!1;
window.ua=class b{constructor(a){this.ca=a.bf;this.wa=null;this.ba="";this.Ya=a.Ze;this.Bb={};this.Ra=this.ta=null;this.Ob=[];this.J=this.xa=null;this.Nc=!1;this.zd=0;this.qb=null;this.Xa=-1;this.Re=()=>this.Ge();this.Wa=[];this.u=a.Td;this.Rb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&la()||(this.ca=!1);this.ca&&fa&&(this.ca=!1);if("playable-ad"===this.u||"instant-games"===this.u)this.ca=!1;if("cordova"===this.u&&this.ca)if(ea){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.Ub=this.qa=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.Ce(c));this.C("runtime","create-job-worker",()=>this.De());"cordova"===this.u?document.addEventListener("deviceready",
()=>this.pd(a)):this.pd(a)}j(){this.sc();this.wa&&(this.wa=this.wa.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Ra&&(this.Ra.j(),this.Ra=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}oe(){return da&&"cordova"===this.u}oc(){const a=navigator.userAgent;return da&&xa.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}me(){return ea}hd(){return ea&&xa.has(this.u)}async pd(a){"macos-wkwebview"===this.u&&this.Cc({type:"ready"});if("playable-ad"===
this.u){this.qa=self.c3_base64files;this.Ub={};await this.ve();for(let d=0,e=a.$a.length;d<e;++d){var c=a.$a[d];this.Ub.hasOwnProperty(c)?a.$a[d]={We:!0,$e:this.Ub[c]}:this.qa.hasOwnProperty(c)&&(a.$a[d]=URL.createObjectURL(this.qa[c]))}a.hc=[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.md(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Ye?this.ba=a.Ye:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),
-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.df&&(this.Bb=a.df);c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Fe(d));this.qb=new self.pe(this);await za(this.qb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.ca?await this.Be(a,c.port2):await this.Ae(a,c.port2)}uc(a){a=this.Bb.hasOwnProperty(a)?this.Bb[a]:a.endsWith("/workermain.js")&&this.Bb.hasOwnProperty("workermain.js")?this.Bb["workermain.js"]:"playable-ad"===this.u&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async jc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.Rb)return a=await this.Cb(d.Ve?a:this.Ya+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}oa(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}od(a){var c=this.ba,d=location.href,e=this.oa(),f=this.ha(),g=window.devicePixelRatio,h=b.gb(),k=a.lf,m=window.cr_previewImageBlobs||this.qa,q=window.cr_previewProjectFileBlobs,C=window.cr_previewProjectFiles,z=window.jf||
"";a=a.Td;var t=(new URLSearchParams(self.location.search)).has("debug"),D=this.qb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:m,previewProjectFileBlobs:q,previewProjectFileSWUrls:C,swClientId:z,exportType:a,isDebug:t,ife:!!self.kf,jobScheduler:{inputPort:D.Mc,outputPort:D.Uc,maxNumWorkers:D.Oe},supportedAudioFormats:ma,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Ya+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Ya+"opus.wasm.wasm",isFileProtocol:this.Rb,isiOSCordova:this.oe(),isiOSWebView:this.oc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Be(a,c){const d=this.uc(a.cf);"preview"===this.u?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const m=q=>{this.ta.removeEventListener("message",m);q.data&&"ok"===q.data.type?h():k()};this.ta.addEventListener("message",m);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,
this.ba)).toString()})})):this.ta=await this.jc(d,this.ba,{type:"module",name:"Runtime",Ve:!0});this.J=document.createElement("canvas");this.J.style.display="none";const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.hc||[],g=a.$a;f=await Promise.all(f.map(h=>this.Ma(h)));g=await Promise.all(g.map(h=>this.Ma(h)));if("cordova"===this.u)for(let h=0,k=a.fc.length;h<k;++h){const m=
a.fc[h],q=m[0];if(q===a.$c||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))m[1]=await this.Ma(q)}this.ta.postMessage(Object.assign(this.od(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.fc,mainProjectScript:a.$c,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...Aa(this.qb)]);this.Ob=B.map(h=>new h(this));this.nd();Ba(this.xa);self.c3_callFunction=(h,k)=>{var m=this.xa;return m.v.kd(m.kb,"js-invoke-function",
{name:h,params:k})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.Eb("runtime","go-to-last-error-script"))}async Ae(a,c){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ob=B.map(g=>new g(this));this.nd();var d=a.$a.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.hc)){var e=[...a.hc].map(g=>g instanceof Blob?URL.createObjectURL(g):
g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Ma(g)));await Promise.all(d.map(g=>ia(g)));d=self.C3_ProjectScriptsStatus;e=a.$c;const f=a.fc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ma(h),await ia(h),"preview"!==this.u||d[g]||this.rd(g,"main script did not run to completion")}catch(k){this.rd(g,k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ma(h),await ia(h);"preview"===this.u&&"object"!==typeof self.ef.gf?(this.Ib(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.od(a),{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:wa}),Ba(this.xa),this.qd(),this.Ra=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ra,a))}rd(a,c){this.Ib();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}qd(){this.Ib()}Ib(){const a=
window.Te;a&&(a.parentElement.removeChild(a),window.Te=null)}async De(){const a=await Ca(this.qb);return{outputPort:a,transferables:[a]}}ze(){if(this.ca)throw Error("not available in worker mode");return this.Ra}Eb(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}kd(a,c,d,e,f){const g=va++,h=new Promise((k,m)=>{ta.set(g,{resolve:k,reject:m})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ee(a);if("result"===c)this.He(a);else if("runtime-ready"===c)this.Ie();else if("alert-error"===c)this.Ib(),alert(a.message);else if("creating-runtime"===c)this.qd();else throw Error(`unknown message '${c}'`);}Ee(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=qa.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Hb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Hb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Hb(f,!1,""+h)}):this.Hb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Hb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}He(a){const c=a.responseId,d=a.isOk;a=a.result;const e=ta.get(c);d?e.resolve(a):e.reject(a);ta.delete(c)}C(a,
c,d){let e=qa.get(a);e||(e=new Map,qa.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static ab(a){if(B.includes(a))throw Error("DOM handler already added");B.push(a)}nd(){for(const a of this.Ob)if("runtime"===a.kb){this.xa=a;return}throw Error("cannot find runtime DOM handler");}Fe(a){this.Eb("debugger","message",a)}Ie(){for(const a of this.Ob)a.bd()}static gb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
ya)}static Jb(a){ya=!!a}md(a){this.Wa.push(a);this.Bc()}Ke(a){a=this.Wa.indexOf(a);if(-1===a)throw Error("invalid callback");this.Wa.splice(a,1);this.Wa.length||this.sc()}Bc(){-1===this.Xa&&this.Wa.length&&(this.Xa=requestAnimationFrame(this.Re))}sc(){-1!==this.Xa&&(cancelAnimationFrame(this.Xa),this.Xa=-1)}Ge(){this.Xa=-1;for(const a of this.Wa)a();this.Bc()}Ca(a){this.xa.Ca(a)}Ka(a){this.xa.Ka(a)}Ac(){this.xa.Ac()}Gb(a){this.xa.Gb(a)}ne(){return!!ma["audio/webm; codecs=opus"]}async Le(a){a=await this.kd("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}re(a){this.Nc=!0;this.zd=a}le(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}jd(a){return!this.le(a)}async Ma(a){return"cordova"===this.u&&(a.startsWith("file:")||this.Rb&&this.jd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Cb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ce(a){const c=a.filename;switch(a.as){case "text":return await this.je(c);
case "buffer":return await this.Cb(c);default:throw Error("unsupported type");}}ed(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async je(a){a=await this.ed(a);return await na(a)}tc(){if(pa.length&&!(8<=A)){A++;var a=pa.shift();this.we(a.filename,a.af,a.Ue)}}Cb(a){return new Promise((c,d)=>{pa.push({filename:a,af:e=>{A--;this.tc();c(e)},Ue:e=>{A--;this.tc();d(e)}});this.tc()})}async we(a,c,d){try{const e=
await this.ed(a),f=await oa(e);c(f)}catch(e){d(e)}}Cc(a){if("windows-webview2"===this.u)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.u)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async ve(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.ue(c,d));await Promise.all(a)}async ue(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),this.Ub[a]=c.str;else{let d=
await this.ye(c);d||(d=this.xe(c));this.qa[a]=d}}async ye(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}xe(a){a=this.Je(a);return this.te(a.data,a.Xe)}Je(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,
c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Xe:a,data:d}}te(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const E=self.ua;
function Da(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Ea=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),F={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Fa={dispatchUserScriptEvent:!0},Ga={dispatchRuntimeEvent:!0};
function Ha(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ia(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function G(b){b=URL.createObjectURL(b);try{return await Ia(b)}finally{URL.revokeObjectURL(b)}}
function Ja(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ka(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await G(b);var d=await Ja(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await G(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await G(b)}
function La(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ma=new Set(["input","textarea","datalist","select"]),Na=new Set(["canvas","body","html"]);function I(b){b.target.tagName&&Na.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Oa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await G(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ka(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Pa=!1;document.addEventListener("pause",()=>Pa=!0);document.addEventListener("resume",()=>Pa=!1);function Ba(b){b.yd=!0;b.Rc=b.v.oa();b.rb=b.v.ha()}async function Qa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ra(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Sa(b){return await self.C3_GetSvgImageSize(b.blob)}function Ta(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ua(b){self.setTimeout(()=>{b.xd=!0},1E3);"cordova"===b.v.u?(document.addEventListener("pause",()=>Va(b,!0)),document.addEventListener("resume",()=>Va(b,!1))):document.addEventListener("visibilitychange",()=>Va(b,document.hidden));return{isSuspended:!(!document.hidden&&!Pa)}}
function Wa(b){b.td||(b.td=!0,window.addEventListener("deviceorientation",a=>{b.$||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},F)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},F)}))}
function Xa(b){b.sd||(b.sd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},F)}}))}async function Ya(b){await Ha(b.url)}
function Za(b,a){b.Ad=a.message;-1===b.Hc&&(b.Hc=setTimeout(()=>{b.Hc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Ad)},250))}function J(b){if(!b.$){var a=E.gb();a&&"any"!==b.Xc&&$a(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ha()})}}function ab(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:E.gb(),innerWidth:b.oa(),innerHeight:b.ha()})}
function Va(b,a){a?b.v.sc():b.v.Bc();l(b,"visibilitychange",{hidden:a})}function db(b,a,c){"Backspace"===c.key&&I(c);if(!b.$){var d=Ea.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},F)}}
function eb(b,a,c,d){b.$||Da(c)||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function fb(b){window!==window.top&&window.focus();gb(b.target)&&document.activeElement&&!gb(document.activeElement)&&document.activeElement.blur()}
function K(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.wb);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},F);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),eb(b,d,c,Fa),b.wb=c.buttons)}}
function hb(b,a,c){if(!b.$&&!Da(c)){var d=b.wb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");n(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},F);b.wb=c.buttons;eb(b,c.type,c,Fa)}}
function L(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];n(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
F)}}function ib(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function jb(b,a,c,d){const e=b.oa(),f=b.ha();b.Za=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.gb()}):10>d&&kb(b,e,f,d+1)}
function kb(b,a,c,d){-1!==b.Za&&clearTimeout(b.Za);b.Za=setTimeout(()=>jb(b,a,c,d),48)}
function $a(b){b=b.Xc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function gb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
E.ab(class extends self.cb{constructor(b){super(b,"runtime");this.Fd=!0;this.yd=!1;this.Za=-1;this.Xc="any";this.sd=this.td=!1;this.cc=document.createElement("div");this.cc.className="c3-screen-reader-text";this.cc.setAttribute("aria-live","polite");document.body.appendChild(this.cc);this.Fa=null;this.$=!1;this.Ad="";this.Hc=-1;this.xd=!1;this.Rc=b.oa();this.rb=b.ha();this.da=this.Ab=0;b.C("canvas","update-size",d=>{var e=this.v;e.Nc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Fd&&(e.style.display="",this.Fd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Qa(d));b.C("runtime","raster-svg-image",d=>Ra(d));b.C("runtime","get-svg-image-size",
d=>Sa(d));b.C("runtime","set-target-orientation",d=>{this.Xc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Ta(d));b.C("runtime","go-to-script",d=>Ta(d));b.C("runtime","before-start-ticking",()=>Ua(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Fa||(this.Fa=document.createElement("div"),this.Fa.id="inspectOutline",document.body.appendChild(this.Fa));var e=this.Fa;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Fa&&(this.Fa.style.display="none")});b.C("runtime","enable-device-orientation",()=>Wa(this));b.C("runtime","enable-device-motion",()=>Xa(this));b.C("runtime","add-stylesheet",d=>Ya(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>this.xc(d));b.C("runtime",
"screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.cc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.J.style.display="";this.v.re(d.duration)});b.C("runtime","export-to-video-progress",d=>Za(this,d));b.C("runtime","exported-to-video",d=>{window.Se({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Se({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||La(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",I);window.addEventListener("gesturehold",I);c.addEventListener("selectstart",I);c.addEventListener("gesturehold",
I);window.addEventListener("touchstart",I,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",I,{passive:!1}),c.addEventListener("pointerdown",I)):c.addEventListener("touchstart",I);this.wb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Oa,{passive:!1});window.addEventListener("wheel",Oa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.yd){var d=this.oa();var e=this.ha();if(this.v.hd()){if(this.xd){if(this.Rc===
d&&e<this.rb){this.Ab=this.rb-e;ib(this,this.rb,this.Ab);d=void 0;break a}0<this.Ab&&(this.Ab=0,ib(this,e,this.Ab))}this.Rc=d;this.rb=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.gb()});this.v.oc()&&(-1!==this.Za&&clearTimeout(this.Za),jb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>J(this));window.addEventListener("webkitfullscreenchange",()=>J(this));window.addEventListener("mozfullscreenchange",()=>
J(this));window.addEventListener("fullscreenerror",d=>ab(this,d));window.addEventListener("webkitfullscreenerror",d=>ab(this,d));window.addEventListener("mozfullscreenerror",d=>ab(this,d));if(b.oc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):La(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(E.Jb(!0),J(this)):"exited-fullscreen"===d?(E.Jb(!1),J(this)):console.warn("Unknown wrapper message: ",d)};this.Sa=new Set;this.Wb=new WeakSet;this.va=!1}bd(){window.addEventListener("focus",()=>{l(this,"window-focus",null,Ga)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}l(this,"window-blur",{parentHasFocus:a},Ga);this.wb=0});window.addEventListener("focusin",a=>{a=a.target;(Ma.has(a.tagName.toLowerCase())||La(a))&&l(this,"keyboard-blur",null,Ga)});window.addEventListener("keydown",a=>db(this,"keydown",a));window.addEventListener("keyup",a=>db(this,"keyup",a));window.addEventListener("dblclick",a=>eb(this,"dblclick",a,F));window.addEventListener("wheel",a=>{this.$||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,
deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},F)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{fb(a);K(this,"pointerdown",a)}),this.v.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{K(this,"pointermove",a)}):window.addEventListener("pointermove",a=>K(this,"pointermove",a)),window.addEventListener("pointerup",a=>K(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>K(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{fb(a);hb(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>hb(this,"pointermove",a)),window.addEventListener("mouseup",a=>hb(this,"pointerup",a)),window.addEventListener("touchstart",a=>{fb(a);L(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>L(this,"pointermove",a)),window.addEventListener("touchend",a=>L(this,"pointerup",a)),window.addEventListener("touchcancel",a=>L(this,"pointercancel",a)));const b=
()=>this.Ac();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.me()&&!this.v.hd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{ib(this,this.ha(),navigator.virtualKeyboard.boundingRect.height)}))}oa(){return this.v.oa()}ha(){return this.v.ha()}Ac(){var b=
[...this.Sa];this.Sa.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.Wb.has(a)||this.Sa.add(a)})}Ca(b){if("function"!==typeof b.play)throw Error("missing play function");this.Wb.delete(b);let a;try{a=b.play()}catch(c){this.Sa.add(b);return}a&&a.catch(()=>{this.Wb.has(b)||this.Sa.add(b)})}Ka(b){this.Sa.delete(b);this.Wb.add(b)}Gb(b){this.va=!!b}xc(b){alert(b.message)}});"use strict";
async function za(b){if(b.Me)throw Error("already initialised");b.Me=!0;var a=b.ya.uc(("playable-ad"===b.ya.u?b.ya.Ya:"")+"dispatchworker.js");b.Fc=await b.ya.jc(a,b.jb,{name:"DispatchWorker"});a=new MessageChannel;b.Mc=a.port1;b.Fc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Uc=await Ca(b)}function Aa(b){return[b.Mc,b.Uc]}
async function Ca(b){const a=b.Gd.length;var c=b.ya.uc(("playable-ad"===b.ya.u?b.ya.Ya:"")+"jobworker.js");c=await b.ya.jc(c,b.jb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Fc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Gd.push(c);return e.port1}
self.pe=class{constructor(b){this.ya=b;this.jb=b.ba;this.jb="preview"===b.u?this.jb+"workers/":this.jb+b.Ya;this.Oe=Math.min(navigator.hardwareConcurrency||2,16);this.Fc=null;this.Gd=[];this.Uc=this.Mc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ua({bf:!0,cf:"workermain.js",$a:["scripts/c3runtime.js"],fc:[],$c:"",Ze:"scripts/",hc:[],Td:"html5"}));"use strict";
async function lb(b,a){a=a.type;let c=!0;0===a?c=await mb():1===a&&(c=await nb());l(b,"permission-result",{type:a,result:c})}async function mb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function nb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.ua.ab(class extends self.cb{constructor(b){super(b,"touch");p(this,"request-permission",a=>lb(this,a))}});"use strict";function ob(){}
function pb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>l(b,"sw-message",a.data))}
function qb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.ua.ab(class extends self.cb{constructor(b){super(b,"browser");this.u="";r(this,[["get-initial-state",a=>{this.u=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
pb(this)],["alert",a=>this.xc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.zc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>qb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.hf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.u||"macos-wkwebview"===this.u)self.ua.Jb(!0),this.v.Cc({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===
a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(ob)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.u||"macos-wkwebview"===
this.u)self.ua.Jb(!1),this.v.Cc({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(ob)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=
Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),
c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{l(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{l(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{l(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{l(this,"backbutton")})}xc(b){alert(b.message)}zc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
"use strict";function rb(b){b.replaceChildren?b.replaceChildren():b.innerHTML=""}function M(b){b=Array.from(b.querySelectorAll("script:not([c3-executed])"));for(const c of b){b=c.parentNode;var a=b.replaceChild;const d=document.createElement("script");d.text=c.text;const e=c.attributes;for(let f=0,g=e.length;f<g;++f){const h=e[f];d.setAttribute(h.name,h.value)}d.setAttribute("c3-executed","");a.call(b,d,c)}}
function N(b,a,c){return a?c?Array.from(b.querySelectorAll(a)):(b=b.querySelector(a))?[b]:[]:[b]}function O(b){return b?{isOk:!0,html:b.innerHTML,text:b.textContent}:{isOk:!1}}
self.ua.ab(class extends self.ke{constructor(b){super(b);v(this,"set-content",(a,c)=>{{const e=c.str,f=c.type,g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)"html"===f?(k.innerHTML=e,M(k)):k.textContent=e;d=O(a)}}catch(h){console.warn("[HTML element] Failed to set content: ",h),d=O(null)}}return d});v(this,"insert-content",(a,c)=>{{const e=c.str,f=c.type,g=c["at-end"]?"beforeend":"afterbegin",h=c.selector;c=c["is-all"];try{const k=N(a,h,c);if(0===
k.length)var d=O(null);else{for(const m of k)"html"===f?(m.insertAdjacentHTML(g,e),M(m)):m.insertAdjacentText(g,e);d=O(a)}}catch(k){console.warn("[HTML element] Failed to insert content: ",k),d=O(null)}}return d});v(this,"remove-content",(a,c)=>{{const e=c["is-clear"],f=c.selector;c=c["is-all"];if(f)try{const g=N(a,f,c);if(0===g.length)var d=O(null);else{for(const h of g)e?rb(h):h.remove();d=O(a)}}catch(g){console.warn("[HTML element] Failed to remove content: ",g),d=O(null)}else rb(a),d=O(a)}return d});
v(this,"set-content-class",(a,c)=>{{const e=c.mode,f=c["class-array"],g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)for(const m of f)switch(e){case "add":k.classList.add(m);break;case "toggle":k.classList.toggle(m);break;case "remove":k.classList.remove(m)}d=O(a)}}catch(h){console.warn("[HTML element] Failed to set class: ",h),d=O(null)}}return d});v(this,"set-content-attribute",(a,c)=>{{const e=c.mode,f=c.attribute,g=c.value,h=c.selector;c=c["is-all"];
try{const k=N(a,h,c);if(0===k.length)var d=O(null);else{for(const m of k)switch(e){case "set":m.setAttribute(f,g);break;case "remove":m.removeAttribute(f)}d=O(a)}}catch(k){console.warn("[HTML element] Failed to set attribute: ",k),d=O(null)}}return d});v(this,"set-content-css-style",(a,c)=>{{const e=c.prop,f=c.value,g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)e.startsWith("--")?k.style.setProperty(e,f):k.style[e]=f;d=O(a)}}catch(h){console.warn("[HTML element] Failed to set style: ",
h),d=O(null)}}return d});v(this,"get-element-box",(a,c)=>{(a=(c=c.selector)?a.querySelector(c):a)?(a=a.getBoundingClientRect(),a={isOk:!0,left:a.left,top:a.top,right:a.right,bottom:a.bottom}):a={isOk:!1};return a});v(this,"insert-img-element",(a,c)=>{a:{const e=c.blobUrl;var d=c.width;const f=c.height,g=c.selector,h=c.insertAt;let k=a;if(g&&(k=a.querySelector(g),!k)){a={isOk:!1};break a}d=new Image(d,f);d.src=e;c.id&&(d.id=c.id);c["class"]&&(d.className=c["class"]);0===h?k.prepend(d):1===h?k.append(d):
k.replaceChildren?k.replaceChildren(d):(rb(k),k.append(d));a=O(a)}return a});v(this,"set-scroll-position",(a,c)=>{a:{const d=c.selector,e=c.direction;c=c.position;if(d&&(a=a.querySelector(d),!a)){c=void 0;break a}"left"===e?a.scrollLeft=c:a.scrollTop=c;c=void 0}return c})}fd(b,a){const c=document.createElement(a.tag);a["style-attribute"]&&c.setAttribute("style",a["style-attribute"]);c.style.position="absolute";var d=a["stop-input-events-mode"];if(0<d){let e=null;1===d?e=f=>{f.target!==c&&f.stopPropagation()}:
2===d&&(e=f=>f.stopPropagation());c.addEventListener("pointerdown",e);c.addEventListener("pointermove",e);c.addEventListener("pointerrawupdate",e);c.addEventListener("pointerup",e);c.addEventListener("mousedown",e);c.addEventListener("mouseup",e);c.addEventListener("dblclick",e)}a["allow-context-menu"]&&c.addEventListener("contextmenu",e=>e.stopPropagation());c.addEventListener("click",e=>{e=e.target;const f=[];for(;e;){f.push({targetId:"string"===typeof e.id?e.id:"",targetClass:"string"===typeof e.className?
e.className:""});if(e===c)break;e=e.parentNode}x(this,"click",b,{chain:f})});c.addEventListener("animationend",e=>{const f=e.target;x(this,"animationend",b,{targetId:"string"===typeof f.id?f.id:"",targetClass:"string"===typeof f.className?f.className:"",animationName:e.animationName})});a.id&&(c.id=a.id);a.className&&(c.className=a.className);a["css-color"]&&(c.style.color=a["css-color"]);a["css-background-color"]&&(c.style.backgroundColor=a["css-background-color"]);a["allow-text-selection"]||(c.style.userSelect=
"none",c.style.webkitUserSelect="none");d=a.str;"html"===a.type?(c.innerHTML=d,M(c)):c.textContent=d;x(this,"initial-content",b,{html:c.innerHTML,text:c.textContent});return c}ld(b,a){b.innerHTML=a.html;M(b)}});"use strict";const sb=180/Math.PI;
async function tb(b,a){if(a.isiOSCordova||a.isSafari)b.Zb=!0;b.Yc=a.timeScaleMode;b.Ld=["equalpower","HRTF","soundfield"][a.panningModel];b.wd=["linear","inverse","exponential"][a.distanceModel];b.Md=a.refDistance;b.Kd=a.maxDistance;b.Od=a.rolloffFactor;if(b.v.Nc)b.Zb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.zd)});else{var c={latencyHint:a.latencyHint};b.Rd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");ub(b);b.g.onstatechange=()=>{"running"!==b.g.state&&ub(b);l(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Oa=b.g.createGain();b.Oa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function vb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,m=a.pos,q=a.panning,C=a.stereoPan;let z=a.off;0<z&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),z=z-a.performanceTime/1E3+a.contextTime):z=z-performance.now()/1E3+b.g.currentTime);b.Hd=g.slice(0);wb(b,g);try{b.R=await xb(b,c,d,e,g,f);if(q){Q(b.R,!0);var t=b.R,D=q.innerAngle,ra=q.outerAngle,sa=q.outerGain;if(t.pb){yb(t,q.x,q.y,q.z,q.angle);var H=self.bb.se;t.ra[0]!==H(D)&&
(t.ra[0]=H(D),t.F.coneInnerAngle=H(D));t.ra[1]!==H(ra)&&(t.ra[1]=H(ra),t.F.coneOuterAngle=H(ra));t.ra[2]!==sa&&(t.ra[2]=sa,t.F.coneOuterGain=sa)}q.hasOwnProperty("uid")&&(b.R.pa=q.uid)}else"number"===typeof C&&0!==C?(R(b.R,!0),zb(b.R,C)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,m,z)}catch(Lb){console.error("[Construct] Audio: error starting playback: ",Lb);return}finally{c=g.join(" ");d=b.yb.get(c);if(!d)throw Error("expected pending tag");d.ad--;0===d.ad&&(d.resolve(),b.yb.delete(c))}u(b)}
async function Ab(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await Bb(b,c);for(const h of S(b,c))if(!h.Qa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.s.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ia=d;h.Pa=g;h.Qd=a}T(b)}async function Cb(b,a){const c=a.tags;a=a.rate;await Bb(b,c);for(const d of S(b,c))d.la!==a&&(d.la=a,d.Da())}async function Db(b,a){const c=a.tags;a=a.pos;await Bb(b,c);for(const d of S(b,c))d.pc(a)}
async function Eb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await xb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function Fb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function Gb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.Zd(b,...e);else if("delay"===c)d=new self.Xd(b,...e);else if("convolution"===c){var g=d=new self.Wd(b,f.ia,...e),h=a.bufferType;g.ud=a.bufferOriginalUrl;g.vd=h}else if("flanger"===c)d=new self.$d(b,...e);else if("phaser"===
c)d=new self.be(b,...e);else if("gain"===c)d=new self.ae(b,...e);else if("stereopan"===c)d=new self.de(b,...e);else if("tremolo"===c)d=new self.ee(b,...e);else if("ringmod"===c)d=new self.ce(b,...e);else if("distortion"===c)d=new self.Yd(b,...e);else if("compressor"===c)d=new self.Vd(b,...e);else if("analyser"===c)d=new self.Ud(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let m=g.ka.get(h);m||(m=[],g.ka.set(h,m));d.Ed=m.length;d.Wc=h;m.push(d);Hb(g,h)}Ib(b)}
async function Jb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Aa()&&1===c||!e.Aa()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ka.values())for(const g of f)g.j();b.ka.clear();b.dc=a.timeScale;b.Ic=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.va=a.isSilent;b.v.Gb(b.va);b.Vb=a.masterVolume;b.Oa.gain.value=
b.Vb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>Gb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Kb(b,f,c)));T(b)}
async function Mb(b,a){try{const c=b.g.suspend(a.time);b.Dd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Eb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Nb(d)),b.Dd=!0);await c}catch(c){Nb(c)}}
function ub(b){b.Pb||(b.Lc=!1,window.addEventListener("pointerup",b.za,!0),window.addEventListener("touchend",b.za,!0),window.addEventListener("click",b.za,!0),window.addEventListener("keydown",b.za,!0),b.Pb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ja)if(g.fb()===c)return await Ob(g),g;if(f)return null;if(e&&(b.Zb||b.Cd)){f=0;for(let h=0,k=b.ja.length;h<k;++h)g=b.ja[h],b.ja[f]=g,g.Aa()?g.j():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.Rd;e&&f&&(b.Cd=!0);c=!e||b.Zb||f?new self.he(b,a,c,d,e,f):new self.fe(b,a,c,d,e);b.ja.push(c);await Ob(c);b.Jd.has(a)||(l(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.Jd.add(a));return c}
function Pb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Qb(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.na()}function Hb(b,a){a=a.toLowerCase();let c=b.na();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.na()):e.U(d[f+1].N())}}for(const f of Rb(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Ga&&b.Sc===a&&(b.Ga.disconnect(),b.Ga.connect(c))}
function*Rb(b,a){if(a)for(const c of b.H)Pb(0<c.ma.length?c.ma[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Sb(b,a,c){return c?b.v.Le(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Tb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.ma;var c=a;for(const e of c){c=!1;for(const f of b)if(Pb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function xb(b,a,c,d,e,f){for(const g of b.H)if(g.fb()===c&&(g.ic()||f))return g.ma=e,g;a=await P(b,a,c,d,f);e="html5"===a.Dc?new self.ge(a.s,a,e):new self.ie(a.s,a,e);b.H.push(e);return e}
function wb(b,a){a=a.join(" ");let c=b.yb.get(a);if(!c){let d=null;c={ad:0,promise:new Promise(e=>d=e),resolve:d};b.yb.set(a,c)}c.ad++}function Bb(b,a){return(b=b.yb.get((0===a.length?b.Hd:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Na.size)u(b);else for(const a of b.H)if(!a.I&&!a.O()){u(b);break}}function Ub(b,a,c,d){l(b,"trigger",{type:a,tags:c,aiid:d})}function Ib(b){b.Oc||(b.Oc=!0,Promise.resolve().then(()=>Vb(b)))}
function Vb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.eb());l(b,"fxstate",{fxstate:a});b.Oc=!1}
async function Kb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,m=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await xb(b,d,e,f,h,g)}catch(C){console.error("[Construct] Audio: error loading audio state: ",C);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Ua[0]=f[0],b.Ua[1]=f[1],b.Ua[2]=f[2],f=d.orient,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],e.setPosition(...b.Ua),e.setOrientation(...b.Ta),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),zb(b,d));c.Play(k,m,q,0);a.isPlaying||c.hb();c.wc(a)}}}function Nb(b){console.error("[Audio] Offline rendering error: ",b)}
self.bb=class extends self.cb{constructor(b){super(b,"audio");this.Oa=this.g=null;this.Pb=this.Lc=!1;this.za=()=>{if(!this.Lc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Pb&&(this.Lc=!0,window.removeEventListener("pointerup",this.za,!0),window.removeEventListener("touchend",this.za,!0),window.removeEventListener("click",this.za,!0),window.removeEventListener("keydown",
this.za,!0),this.Pb=!1)}};this.ja=[];this.H=[];this.R=null;this.Hd=[];this.Jd=new Set;this.Id=-1;this.yb=new Map;this.Vb=1;this.va=!1;this.Yc=0;this.dc=1;this.Ic=0;this.Ld="HRTF";this.wd="inverse";this.Md=600;this.Kd=1E4;this.Od=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.Cd=this.Zb=!1;this.Rd=this.v.ne();this.ka=new Map;this.Na=new Set;this.Dd=this.Oc=!1;this.Sc="";this.Ga=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ga&&this.Ga.disconnect();this.Sc=c.toLowerCase();this.Ga=this.g.createMediaStreamSource(a);
this.Ga.connect(Qb(this,this.Sc))};this.Nb=null;self.C3Audio_GetOutputStream=()=>{this.Nb||(this.Nb=this.g.createMediaStreamDestination(),this.Oa.connect(this.Nb));return this.Nb.stream};self.C3Audio_DOMInterface=this;r(this,[["create-audio-context",a=>tb(this,a)],["play",a=>vb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ba()}],["stop-all",()=>{for(const a of this.H)a.Ba()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.hb():d.Fb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>Ab(this,a)],["set-master-volume",a=>{this.Vb=a.vol;this.Oa.gain.value=this.Vb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Wb(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.v.Gb(this.va);for(const c of this.H)c.Kb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.qc(a)}],["set-playback-rate",a=>Cb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),zb(d,a)}],["seek",a=>Db(this,a)],["preload",a=>Eb(this,a)],["unload",a=>Fb(this,a)],["unload-all",()=>{for(const a of this.ja)a.j();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.rc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Gb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ka.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Ib(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ka.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ka.delete(a);Hb(this,a)}}],["tick",a=>{this.dc=a.timeScale;this.Ic=a.gameTime;this.Id=a.tickCount;if(0!==this.Yc)for(var c of this.H)c.Da();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==
c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.pa===a&&yb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Jb(this,a)],["offline-render-audio",a=>Mb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}W(){return this.g}na(){return this.Oa}Db(){return this.va}Ca(b){this.v.Ca(b)}Ka(b){this.v.Ka(b)}La(){for(var b of this.Na)b.La();
b=this.g.currentTime;for(var a of this.H)a.La(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.eb());l(this,"state",{tickCount:this.Id,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Na].map(c=>({tag:c.Wc,index:c.Ed,peak:c.Va,rms:c.Nd,binCount:c.l.frequencyBinCount,freqBins:c.Bd}))});0===a.length&&0===this.Na.size&&this.Qb&&(this.v.Ke(this.Sd),this.Qb=!1)}static se(b){return b*sb}static gd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static qe(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.ua.ab(self.bb);"use strict";function Ob(b){b.Tb||(b.Tb=b.vc());return b.Tb}self.cd=class{constructor(b,a,c,d,e){this.s=b;this.Qe=a;this.Ha=c;this.T=d;this.Ne=e;this.Dc="";this.Tb=null}j(){this.Tb=this.s=null}vc(){}W(){return this.s.W()}lc(){return this.Qe}fb(){return this.Ha}kc(){return this.T}Aa(){return this.Ne}ga(){}};"use strict";
self.fe=class extends self.cd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Dc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.sb=this.tb=null;this.M.addEventListener("canplaythrough",()=>!0);this.xb=this.W().createGain();this.vb=null;this.M.addEventListener("canplay",()=>{this.tb&&(this.tb(),this.sb=this.tb=null);!this.vb&&this.M&&(this.vb=this.W().createMediaElementSource(this.M),this.vb.connect(this.xb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ha}' error: `,f);this.sb&&(this.sb(f),this.sb=this.tb=null)})}j(){Tb(this.s,this);this.xb.disconnect();this.xb=null;this.vb.disconnect();this.vb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}vc(){return new Promise((b,a)=>{this.tb=b;this.sb=a;this.M.src=this.Ha})}V(){return this.M}ga(){return this.M.duration}};"use strict";
async function Xb(b){if(b.Ea)return b.Ea;var a=b.s.v;if("cordova"===a.u&&a.jd(b.Ha)&&a.Rb)b.Ea=await a.Cb(b.Ha);else{a=await fetch(b.Ha);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ea=await a.arrayBuffer()}}async function Yb(b){if(b.ia)return b.ia;b.ia=await Sb(b.s,b.Ea,b.Pe);b.Ea=null}
self.he=class extends self.cd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Dc="webaudio";this.ia=this.Ea=null;this.Pe=!!f}j(){Tb(this.s,this);this.ia=this.Ea=null;super.j()}async vc(){try{await Xb(this),await Yb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ha}': `,b)}}ga(){return this.ia?this.ia.duration:0}};"use strict";let Zb=0;
function Q(b,a){a=!!a;b.pb!==a&&(b.pb=a,b.pb?(R(b,!1),b.F||(b.F=b.W().createPanner(),b.F.panningModel=b.s.Ld,b.F.distanceModel=b.s.wd,b.F.refDistance=b.s.Md,b.F.maxDistance=b.s.Kd,b.F.rolloffFactor=b.s.Od),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.na())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.na())))}
function R(b,a){a=!!a;b.Sb!==a&&(b.Sb=a,b.Sb?(Q(b,!1),b.fa=b.W().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.na())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.na())))}function zb(b,a){b.Sb&&b.Vc!==a&&(b.fa.pan.value=a,b.Vc=a)}function U(b,a){b.Ia=a;b.G.gain.cancelScheduledValues(0);b.Pa=-1;b.G.gain.value=b.mc()}function Wb(b,a){a=!!a;b.Qa!==a&&(b.Qa=a,b.Kb())}
function yb(b,a,c,d,e){if(b.pb){var f=b.Ua,g=b.Ta,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Pc?b.s.Ic:performance.now()/1E3}
self.dd=class{constructor(b,a,c){this.s=b;this.P=a;this.ma=c;this.Lb=Zb++;this.G=this.W().createGain();this.G.connect(this.na());this.F=null;this.pb=!1;this.Ua=[0,0,0];this.Ta=[0,0,0];this.ra=[0,0,0];this.fa=null;this.Sb=!1;this.Vc=0;this.I=!0;this.Y=this.sa=this.K=!1;this.Ia=1;this.Qa=!1;this.la=1;b=this.s.Yc;this.Pc=1===b&&!this.Aa()||2===b;this.Pa=this.pa=-1;this.Qd=!1}j(){this.P=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}W(){return this.s.W()}na(){return Qb(this.s,0<this.ma.length?this.ma[0]:"")}lc(){return this.P.lc()}fb(){return this.P.fb()}kc(){return this.P.kc()}Aa(){return this.P.Aa()}O(){}ic(){}IsPlaying(){return!this.I&&!this.K&&!this.O()}Ja(){}ga(){return this.P.ga()}Play(){}Ba(){}hb(){}Fb(){}La(b){-1!==this.Pa&&b>=this.Pa&&(this.Pa=-1,this.Qd&&this.Ba(),Ub(this.s,"fade-ended",this.ma,this.Lb))}mc(){const b=this.Ia;return isFinite(b)?b:0}Db(){return this.s.Db()}Kb(){}qc(){}Da(){}pc(){}rc(){}nc(){}eb(){var b=
this.Lb,a=this.ma,c=this.ga(),d=-1===this.Pa?this.Ia:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ua,orient:this.Ta,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ja(),playbackRate:this.la,uid:this.pa,bufferOriginalUrl:this.lc(),bufferUrl:"",bufferType:this.kc(),isMusic:this.Aa(),isLooping:this.Y,isMuted:this.Qa,resumePosition:this.nc(),pan:f,stereoPan:this.fa?
this.Vc:null}}wc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Da());Wb(this,b.isMuted)}};"use strict";
self.ge=class extends self.dd{constructor(b,a,c){super(b,a,c);this.P.xb.connect(this.G);this.P.onended=()=>this.yc()}j(){this.Ba();this.P.xb.disconnect();super.j()}V(){return this.P.V()}yc(){this.I=!0;this.pa=-1;Ub(this.s,"ended",this.ma,this.Lb)}O(){return this.V().ended}ic(){return this.I?!0:this.O()}Ja(){let b=this.V().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.V();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.fb()}' to position '${c}': `,e)}this.s.Ca(d);this.K=this.I=!1;this.Y=b;this.la=1}Ba(){const b=this.V();b.paused||b.pause();this.s.Ka(b);this.I=!0;this.K=!1;this.pa=-1}hb(){if(!(this.K||this.I||this.O())){var b=this.V();b.paused||b.pause();this.s.Ka(b);this.K=!0}}Fb(){!this.K||this.I||this.O()||(this.s.Ca(this.V()),this.K=!1)}Kb(){this.V().muted=this.Qa||this.Db()}qc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.V().loop=b)}Da(){let b=this.la;this.Pc&&(b*=this.s.dc);try{this.V().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}pc(b){if(!this.I&&!this.O())try{this.V().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}nc(){return this.Ja()}rc(b){b?this.IsPlaying()?(this.V().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.s.Ca(this.V()),this.sa=!1)}};"use strict";
function W(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.ib=null}
self.ie=class extends self.dd{constructor(b,a,c){super(b,a,c);this.o=null;this.Xb=d=>this.yc(d);this.Kc=!0;this.ib=null;this.S=this.Yb=this.$b=0;this.Tc=1}j(){this.Ba();W(this);this.Xb=null;super.j()}yc(b){this.K||this.sa||b.target!==this.ib||(this.I=this.Kc=!0,this.pa=-1,W(this),Ub(this.s,"ended",this.ma,this.Lb))}O(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Kc}ic(){return!this.o||this.I?!0:this.O()}Ja(){let b;b=this.K?this.S:this.Yb+(V(this)-this.$b)*this.la;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.Tc=1;U(this,a);W(this);this.o=this.W().createBufferSource();this.o.buffer=this.P.ia;this.o.connect(this.G);this.ib=this.o;this.o.onended=this.Xb;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Kc=!1;this.Y=b;this.la=1;this.$b=V(this);this.Yb=c}Ba(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.pa=-1}hb(){this.K||this.I||this.O()||(this.S=this.Ja(),this.Y&&(this.S%=this.ga()),this.K=!0,this.o.stop(0))}Fb(){!this.K||this.I||this.O()||(W(this),this.o=
this.W().createBufferSource(),this.o.buffer=this.P.ia,this.o.connect(this.G),this.ib=this.o,this.o.onended=this.Xb,this.o.loop=this.Y,U(this,this.Ia),this.Da(),this.o.start(0,this.S),this.$b=V(this),this.Yb=this.S,this.K=!1)}mc(){return super.mc()*this.Tc}Kb(){this.Tc=this.Qa||this.Db()?0:1;U(this,this.Ia)}qc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Da(){let b=this.la;this.Pc&&(b*=this.s.dc);this.o&&(this.o.playbackRate.value=b)}pc(b){this.I||this.O()||(this.K?this.S=b:(this.hb(),this.S=
b,this.Fb()))}nc(){return this.S}rc(b){b?this.IsPlaying()?(this.sa=!0,this.S=this.Ja(),this.Y&&(this.S%=this.ga()),this.o.stop(0)):this.sa=!1:this.sa&&(W(this),this.o=this.W().createBufferSource(),this.o.buffer=this.P.ia,this.o.connect(this.G),this.ib=this.o,this.o.onended=this.Xb,this.o.loop=this.Y,U(this,this.Ia),this.Da(),this.o.start(0,this.S),this.$b=V(this),this.Yb=this.S,this.sa=!1)}wc(b){super.wc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.W();this.Ed=-1;this.T=this.Wc="";this.m=null}j(){this.g=null}N(){}U(){}eb(){return{type:this.T,tag:this.Wc,params:this.m}}}
self.Zd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.Xd=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.ub=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.mb=X(this);this.mb.gain.value=c;this.A.connect(this.ub);this.A.connect(this.h);this.ub.connect(this.i);this.ub.connect(this.X);this.X.connect(this.mb);this.mb.connect(this.ub)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.ub.disconnect();
this.X.disconnect();this.mb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.bb.gd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.mb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.Wd=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.vd=this.ud="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.lb=this.g.createConvolver();this.lb.normalize=c;this.lb.buffer=a;this.A.connect(this.lb);this.A.connect(this.h);this.lb.connect(this.i)}j(){this.A.disconnect();this.lb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}eb(){const b=super.eb();b.bufferOriginalUrl=this.ud;b.bufferUrl="";b.bufferType=this.vd;return b}};
self.$d=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.ob=X(this);this.ob.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.ob);this.ob.connect(this.X);this.B.connect(this.L);
this.L.connect(this.X.delayTime);this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.X.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.ob.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.ob.gain,a/100,c,d)}}};
self.be=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.ae=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.bb.gd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.de=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.ee=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.ce=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.zb=X(this);this.zb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.zb.gain);this.B.start(0);this.A.connect(this.zb);this.A.connect(this.h);this.zb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.zb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.Yd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.A=X(this);this.bc=X(this);this.ac=X(this);b=d;.01>b&&(b=.01);this.bc.gain.value=b;this.ac.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.ec=this.g.createWaveShaper();this.Ec=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ec[32768+e]=f,this.Ec[32768-
e-1]=-f;this.ec.curve=this.Ec;this.A.connect(this.bc);this.A.connect(this.h);this.bc.connect(this.ec);this.ec.connect(this.ac);this.ac.connect(this.i)}j(){this.A.disconnect();this.bc.disconnect();this.ec.disconnect();this.ac.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Vd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.Ud=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Bd=new Float32Array(this.l.frequencyBinCount);this.Pd=new Uint8Array(a);this.Nd=this.Va=0;b=this.s;b.Na.add(this);T(b)}j(){this.s.Na.delete(this);this.l.disconnect();super.j()}La(){this.l.getFloatFrequencyData(this.Bd);this.l.getByteTimeDomainData(this.Pd);const b=this.l.fftSize;let a=this.Va=0;for(var c=0;c<b;++c){let d=(this.Pd[c]-
128)/128;0>d&&(d=-d);this.Va<d&&(this.Va=d);a+=d*d}c=self.bb.qe;this.Va=c(this.Va);this.Nd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
